{
    "models": [
        {
            "type": "Sphere",
            "center": [
                -5.0,
                -5.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.0,
                "roughness": 0.0,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                -5.0,
                -2.5,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.25,
                "roughness": 0.0,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                -5.0,
                0.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.5,
                "roughness": 0.0,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                -5.0,
                2.5,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.75,
                "roughness": 0.0,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                -5.0,
                5.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 1.0,
                "roughness": 0.0,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                -2.5,
                -5.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.0,
                "roughness": 0.25,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                -2.5,
                -2.5,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.25,
                "roughness": 0.25,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                -2.5,
                0.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.5,
                "roughness": 0.25,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                -2.5,
                2.5,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.75,
                "roughness": 0.25,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                -2.5,
                5.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 1.0,
                "roughness": 0.25,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                0.0,
                -5.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.0,
                "roughness": 0.5,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                0.0,
                -2.5,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.25,
                "roughness": 0.5,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                0.0,
                0.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.5,
                "roughness": 0.5,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                0.0,
                2.5,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.75,
                "roughness": 0.5,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                0.0,
                5.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 1.0,
                "roughness": 0.5,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                2.5,
                -5.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.0,
                "roughness": 0.75,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                2.5,
                -2.5,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.25,
                "roughness": 0.75,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                2.5,
                0.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.5,
                "roughness": 0.75,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                2.5,
                2.5,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.75,
                "roughness": 0.75,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                2.5,
                5.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 1.0,
                "roughness": 0.75,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                5.0,
                -5.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.0,
                "roughness": 1.0,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                5.0,
                -2.5,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.25,
                "roughness": 1.0,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                5.0,
                0.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.5,
                "roughness": 1.0,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                5.0,
                2.5,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 0.75,
                "roughness": 1.0,
                "ior": 1.0,
                "normal_texture": null
            }
        },
        {
            "type": "Sphere",
            "center": [
                5.0,
                5.0,
                0
            ],
            "radius": 1.0,
            "material": {
                "albedo": [
                    1.0,
                    0.0,
                    0.0
                ],
                "emissive": [
                    0.0,
                    0.0,
                    0.0
                ],
                "opacity": 1.0,
                "metalness": 1.0,
                "roughness": 1.0,
                "ior": 1.0,
                "normal_texture": null
            }
        }
    ],
    "camera": {
        "transform": [
            [
                1.0,
                0.0,
                0.0,
                0.0
            ],
            [
                0.0,
                1.0,
                1.7881393e-07,
                0.0
            ],
            [
                0.0,
                -1.7881393e-07,
                1.0,
                0.0
            ],
            [
                0.0,
                0.0,
                25.0,
                1.0
            ]
        ],
        "fov": 0.6911112,
        "zfar": 100.0,
        "znear": 0.1
    },
    "lights": [
        {
            "type": "Point",
            "position": [
                -2.5,
                -2.5,
                8
            ],
            "color": [
                1000.0,
                1000.0,
                1000.0
            ],
            "size": 0.1
        },
        {
            "type": "Point",
            "position": [
                -2.5,
                2.5,
                8
            ],
            "color": [
                1000.0,
                1000.0,
                1000.0
            ],
            "size": 0.1
        },
        {
            "type": "Point",
            "position": [
                2.5,
                -2.5,
                8
            ],
            "color": [
                1000.0,
                1000.0,
                1000.0
            ],
            "size": 0.1
        },
        {
            "type": "Point",
            "position": [
                2.5,
                2.5,
                8
            ],
            "color": [
                1000.0,
                1000.0,
                1000.0
            ],
            "size": 0.1
        }
    ],
    "background": [
        0.051,
        0.051,
        0.051
    ]
}