[package]
name = "path-tracer"
version = "0.1.0"
authors = ["Florian Amsallem <florian.amsallem@epita.fr>", "Alexandre Lamure <alexandre.lamure@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33.1", features = ["yaml"]}
cgmath="0.17.0"
tobj="2.0.2"
image="0.23.6"