[package]
name = "path-tracer"
version = "0.1.0"
authors = ["Florian Amsallem <florian.amsallem@epita.fr>", "Alexandre Lamure <alexandre.lamure@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath="0.18.0"
clap = {version = "2.33.3", features = ["yaml"]}
easy-gltf = "0.1.4"
image="0.23.14"
kdtree-ray = "0.1.2"
pbr = "1.0.4"
rayon = "1.5.0"
yaml-rust = "0.4.5"
rand = "0.8.3"
