[package]
name = "path-tracer"
version = "0.1.0"
authors = ["Florian Amsallem <florian.amsallem@epita.fr>", "Alexandre Lamure <alexandre.lamure@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath="0.17.0"
clap = {version = "2.33.1", features = ["yaml"]}
easy-gltf = "0.1.2"
image="0.23.12"
pbr = "1.0.3"
rayon = "1.3.1"
yaml-rust = "0.4.4"
